# Generated by Django 5.0.6 on 2024-07-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_company_related_departments_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='email',
        ),
        migrations.RemoveField(
            model_name='department',
            name='head',
        ),
        migrations.RemoveField(
            model_name='department',
            name='phone',
        ),
    ]
