# Generated by Django 5.0.6 on 2024-07-07 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_department_email_remove_department_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='related_departments',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='duties',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='company',
            name='num_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duties', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.employee')),
            ],
        ),
    ]
