# Generated by Django 5.0.6 on 2024-07-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_company_related_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
