# Generated by Django 5.0.6 on 2024-07-08 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.employee'),
        ),
    ]
