# Generated by Django 5.0.6 on 2024-07-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_role_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
