# Generated by Django 5.0.6 on 2024-07-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_role_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
