# Generated by Django 5.0.6 on 2024-07-10 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_by',
        ),
    ]
