# Generated by Django 5.0.6 on 2024-07-10 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_uploadedfile_uploaded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='registartion_number',
            new_name='registration_number',
        ),
    ]
