# Generated by Django 5.0.6 on 2024-07-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_uploadedfile_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
