# Generated by Django 5.0.6 on 2024-07-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_user_is_staff_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_reg_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
