# Generated by Django 5.0.6 on 2024-07-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_user_company_reg_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company_reg_number',
            new_name='company',
        ),
    ]
